server: 
  port: 8080
  servlet: 
    context-path: /
    
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver ##com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flowabletest?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  druid:
    initialSize: 2
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    stat-view-servlet: 
      allow: 
      login-username: admin
      login-password: 123456
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  type-aliases-package: cn.gzsendi
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
 

flowable:
#关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true
  common:
    app:
#     目前先设置一个正确但是不一定可用的url地址
      idm-url: http://localhost:8080/flowable-idm1
      idm-admin:
#       需要设置一个密码，目前先设置，后期不使用
        password: test
#       默认user为admin，这个地方可设置可不设置
        user: admin1